const data = {
    products: [
        {
            _id: 1,
            name: 'iPhone 12 Pro',
            category: 'Smartphone',
            image: "./images/iphone.jpg",
            price: 1200,
            countInStock: 10,
            brand: 'Apple',
            rating: 4.5,
            numReviews: 10,
            description: 'iPhone 12 Pro',
        },
        {
            _id: 2,
            name: 'iPhone 12 Pro',
            category: 'Smartphone',
            image: "./images/iphone.jpg",
            price: 1200,
            countInStock: 10,
            brand: 'Apple',
            rating: 4.5,
            numReviews: 10,
            description: 'iPhone 12 Pro',
        },
        {
            _id: 3,
            name: 'iPhone 12 Pro',
            category: 'Smartphone',
            image: "./images/iphone.jpg",
            price: 1200,
            countInStock: 10,
            brand: 'Apple',
            rating: 4.5,
            numReviews: 10,
            description: 'iPhone 12 Pro',
        },
        {
            _id: 4,
            name: 'iPhone 12 Pro',
            category: 'Smartphone',
            image: "./images/iphone.jpg",
            price: 1200,
            countInStock: 10,
            brand: 'Apple',
            rating: 4.5,
            numReviews: 10,
            description: 'iPhone 12 Pro',
        },
        {
            _id: 5,
            name: 'iPhone 12 Pro',
            category: 'Smartphone',
            image: "./images/iphone.jpg",
            price: 1200,
            countInStock: 10,
            brand: 'Apple',
            rating: 4.5,
            numReviews: 10,
            description: 'iPhone 12 Pro',
        },
        {
            _id: 6,
            name: 'iPhone 12 Pro',
            category: 'Smartphone',
            image: "./images/iphone.jpg",
            price: 1200,
            countInStock: 10,
            brand: 'Apple',
            rating: 4.5,
            numReviews: 10,
            description: 'iPhone 12 Pro',
        },
    ]
}

export default data;